version: '3.8'
services:
  about-me:
    build: .
    ports:
      - "5175:5175"
    volumes:
    - ./src:/app/src
    - ./public:/app/public
    - ./node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev -- --host --port 5175
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
